using System.Collections;
using System.Collections.Generic;
using UnityEngine;


namespace Sources.InGame.BattleObject.Character
{


    public class CharacterController : MonoBehaviour
    {
        private CharacterStatus characterStatus; // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½X

        private void Start()
        {
            // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½ï¿½ï¿½æ“¾ï¿½Ü‚ï¿½ï¿½Íï¿½ï¿½ï¿½ï¿½ï¿½
            characterStatus = GetComponent<CharacterStatus>();
        }

        private void FixedUpdate()
        {
            if (characterStatus.IsDead)
            {
                // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Sï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Íï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½
                return;
            }

            // ï¿½Lï¿½[ï¿½ï¿½ï¿½Í‚ÉŠï¿½Ã‚ï¿½ï¿½Äï¿½Ô‘Jï¿½Ú‚ğ§Œï¿½
            if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.S) ||
                Input.GetKey(KeyCode.D))
            {
                // WASDï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ô‚ï¿½Runï¿½ï¿½Ô‚É‘Jï¿½ï¿½
                characterStatus.UpdateStatus();
                //SetState(Character.Character_State.Run);
            }
            else if (Input.GetKeyDown(KeyCode.E))
            {
                // Eï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ASkill1ï¿½ğ”­“ï¿½
                characterStatus.UseSkill1();
            }
            else if (Input.GetKeyDown(KeyCode.Q))
            {
                // Qï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ASkill2ï¿½ğ”­“ï¿½
                characterStatus.UseSkill2();
            }
            else if (Input.GetKeyDown(KeyCode.X))
            {
                // Rï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ASpecialï¿½ğ”­“ï¿½
                characterStatus.UseSpecial();
            }
            else
            {
                // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½ï¿½Idleï¿½ï¿½Ô‚É‘Jï¿½ï¿½
                characterStatus.UpdateStatus();
                //SetState(Character.Character_State.Idle);
            }

            // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìï¿½ï¿½Sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
        }
    }
}