using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;
using R3;
using Sources.InGame.BattleObject.Skill;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine;


namespace Sources.InGame.BattleObject.Character
{
    public class CharacterStatus : MonoBehaviour
    {
        [SerializeField] private int minHP = 0; // ï¿½Åï¿½ï¿½ï¿½HP
        [SerializeField] private int maxHP = 100; // ï¿½Å‘ï¿½ï¿½HP
        [SerializeField] private float moveSpeed = 5f; // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½x
        [SerializeField] private float Skill1CoolDown = 5f;
        [SerializeField] private float Skill2CoolDown = 8f;
        [SerializeField] private float SpecialCoolDown = 10f;
        [SerializeField] GameObject[] skillPrefab;
        private BuffManager _buffManager;

        private bool isDamageTaken = false; // ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ó‚¯‚ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½

        private float skill1CooldownTimer = 0f; // Skill1ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[
        private float skill2CooldownTimer = 0f; // Skill2ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[
        private float specialCooldownTimer = 0f; // Specialï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[

        private HitPoint _hitPoint;
        
        public GameObject[] GetSkillPrefab
        {
            get { return skillPrefab; }
        }

        public void SetSkillPrefab(GameObject[] skill)
        {
            skillPrefab = skill;
        }

        public int CurrentHP
        {
            get { return _hitPoint.Hp.CurrentValue; }
        }

        public int MaxHP
        {
            get { return maxHP; }
        }

        public int MinHP
        {
            get { return minHP; }
        }

        public ReadOnlyReactiveProperty<bool> IsDead
        {
            get { return _hitPoint.IsDead; }
        }

        public void SetBuff(BuffType buffType, float value, float length)
        {
            _buffManager.SetBuff(buffType, value, length);
        }
        
        public void SetBuff(SkillManager.SkillType buffType, float value, float length)
        {
            switch (buffType)
            {
                case SkillManager.SkillType.BufAttack:
                    _buffManager.SetBuff(BuffType.AttackUp, value, length);
                    break;
                case SkillManager.SkillType.BufSpeed:
                    _buffManager.SetBuff(BuffType.MoveSpeedUp, value, length);
                    break;
                default:
                    throw new NotImplementedException();
            }
        }

        public float GetBuff(BuffType buffType)
        {
            return _buffManager.GetBuffSum(buffType);
        }

        public void Revival()
        {
            _hitPoint.Revival();
        }

        public float MoveSpeed
        {
            get { return moveSpeed; }
        }

        public void Damage(int value)
        {
            _hitPoint.Damage(value);
        }

        public void Heal(int value)
        {
            _hitPoint.Heal(value);
        }

        public void SetMoveSpeed(float speed)
        {
            if (speed > 0)
                moveSpeed = speed;
        }

        private void Awake()
        {
            _buffManager = new BuffManager();
            _hitPoint = new HitPoint(maxHP);            
        }

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìï¿½Ô‚ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
        private void Update()
        {
            UpdateStatus();
        }

        public void UpdateStatus()
        {
            if (IsDead.CurrentValue)
                return;

            // Skill1ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½ï¿½Xï¿½V
            if (skill1CooldownTimer >= 0f)
            {
                skill1CooldownTimer -= Time.deltaTime;
            }

            // Skill2ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½ï¿½Xï¿½V
            if (skill2CooldownTimer >= 0f)
            {
                skill2CooldownTimer -= Time.deltaTime;
            }

            // Specialï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½ï¿½Xï¿½V
            if (specialCooldownTimer >= 0f)
            {
                specialCooldownTimer -= Time.deltaTime;
            }
        }

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½Lï¿½ï¿½1ï¿½ğ”­“ï¿½ï¿½ï¿½ï¿½ï¿½
        public bool UseSkill1()
        {
            if (skill1CooldownTimer <= 0f)
            {
                Debug.Log("use skill1");
                // ï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½İ’ï¿½
                skill1CooldownTimer = Skill1CoolDown;
                return true;
            }
            else
            {
                // Debug.Log("cool time of skill1" + (skill1CooldownTimer).ToString("F2"));
                return false;
            }
        }

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½Lï¿½ï¿½2ï¿½ğ”­“ï¿½ï¿½ï¿½ï¿½ï¿½
        public bool UseSkill2()
        {
            if (skill2CooldownTimer <= 0f)
            {
                Debug.Log("use skill2");
                // ï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½İ’ï¿½
                skill2CooldownTimer = Skill2CoolDown;
                return true;
            }
            else
            {
                // Debug.Log("cool time of skill2" + (skill2CooldownTimer).ToString("F2"));
                return false;
            }
        }

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½Specialï¿½ğ”­“ï¿½ï¿½ï¿½ï¿½ï¿½
        public bool UseSpecial()
        {
            if (specialCooldownTimer <= 0f)
            {
                Debug.Log("use special");
                // ï¿½Nï¿½[ï¿½ï¿½ï¿½_ï¿½Eï¿½ï¿½ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½İ’ï¿½
                specialCooldownTimer = SpecialCoolDown;
                return true;
            }
            else
            {
                // Debug.Log("cool time of special" + (specialCooldownTimer).ToString("F2"));
                return false;
            }
        }

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Ìï¿½ï¿½Sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½

        public float GetSkill1Cool()
        {
            return Skill1CoolDown;
        }

        public float GetSkill2Cool()
        {
            return Skill2CoolDown;
        }

        public float GetSpecialCool()
        {
            return SpecialCoolDown;
        }

        public float GetCurrentSkill1Cool()
        {
            return skill1CooldownTimer;
        }

        public float GetCurrentSkill2Cool()
        {
            return skill2CooldownTimer;
        }

        public float GetCurrentSpecialCool()
        {
            return specialCooldownTimer;
        }
    }

}